-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: BBay, v3 by logangregg624@gmail.com ******

-- ************************************** `user`
CREATE TABLE `user`
(
 `username`         varchar(20) NOT NULL ,
 `firstName`        varchar(20) NOT NULL ,
 `lastName`         varchar(30) NULL ,
 `accountType`      varchar(7) NOT NULL ,
 `birthDate`        date NOT NULL ,
 `email`            varchar(50) NOT NULL ,
 `city`             varchar(30) NOT NULL ,
 `state`            varchar(2) NOT NULL ,
 `phoneNum`         varchar(20) NOT NULL ,
 `streetAddress`    varchar(50) NOT NULL ,
 `accountStartDate` date NOT NULL ,
 `accountEndDate`   date NULL ,

PRIMARY KEY (`username`)
);
-- ************************************** `item`


CREATE TABLE `item`
(
 `itemID`      serial NOT NULL ,
 `name`        varchar(30) NOT NULL ,
 `sellerID`    varchar(20) NOT NULL ,
 `category`    varchar(20) NOT NULL ,
 `subcategory` varchar(20) NOT NULL ,
 `use`         varchar(50) NOT NULL ,
 `buyNowPrice` float NOT NULL ,

PRIMARY KEY (`itemID`),
KEY `KY_item_sellerID` (`sellerID`),
CONSTRAINT `FK_item_sellerID` FOREIGN KEY (`sellerID`) REFERENCES `user` (`username`)
);

-- ************************************** `bid`

 CREATE TABLE `bid`
 (
  `bidID`          serial NOT NULL ,
  `bid_price`      float NOT NULL ,
  `itemID`         BIGINT UNSIGNED NOT NULL,
  `username`       varchar(20) NOT NULL ,
  `bid-start-date` date NOT NULL ,
  `bid-end-date`   date NULL ,

 PRIMARY KEY (`bidID`),
 KEY `KY_bid_username` (`username`),
 CONSTRAINT `FK_bid_username` FOREIGN KEY (`username`) REFERENCES `user` (`username`),
 KEY `KY_bid_itemID` (`itemID`),
 CONSTRAINT `FK_bid_itemID` FOREIGN KEY  (`itemID`) REFERENCES `item` (`itemID`)
 );
-- -- ************************************** `transaction`

CREATE TABLE `transaction`
 (
  `transactionID`        serial NOT NULL ,
  `processingIsComplete` binary NOT NULL ,
  `bidID`                BIGINT UNSIGNED NOT NULL ,
  `transact-date`        date NOT NULL ,

 PRIMARY KEY (`transactionID`),
 KEY `KY_transaction_bidID` (`bidID`),
 CONSTRAINT `FK_transaction_bidID` FOREIGN KEY (`bidID`) REFERENCES `bid` (`bidID`)
 );

 -- -- ************************************** `profile`
  CREATE TABLE `profile`
 (
  `profileID`   serial NOT NULL ,
  `description` varchar(200) NOT NULL ,
  `username`    varchar(20) NOT NULL ,

 PRIMARY KEY (`profileID`),
 KEY `KY_profile_username` (`username`),
 CONSTRAINT `FK_profile_username` FOREIGN KEY (`username`) REFERENCES `user` (`username`)
 );
 
-- -- ************************************** `review`

 CREATE TABLE `review`
 (
  `reviewID`  serial NOT NULL ,
  `rating`    int NOT NULL ,
  `profileID` BIGINT UNSIGNED NOT NULL ,
  `comment`   varchar(400) NOT NULL ,

 PRIMARY KEY (`reviewID`),
 KEY `KY_review_profileID` (`profileID`),
 CONSTRAINT `FK_review_profileID` FOREIGN KEY (`profileID`) REFERENCES `profile` (`profileID`)
 );
 
 
INSERT INTO user (username, firstname, lastname, accountType, birthDate, email, city, `state`, phoneNum, streetAddress, accountStartDate)
VALUES
('Jeremy_wade31', 'Jeremy', 'Wade', 'User', '2004-12-22', 'mrjfootball11@gmail.com', 'Fargo', 'ND', '(701) 789-1432', '8607 Key Circle Dr. 57108', '2022-12-08' ),
('Johnloveslife', 'John', 'Love', 'User', '1999-08-17', 'JohnLovelol@gmail.com', 'SiouxFalls', 'SD', '(605) 759-8756', '4812 Candy Lane 57107', '2022-01-18' ),
('SarahWolfie', 'Sarah', 'Wolfe', 'User', '2002-03-29', 'WolfQueenw@gmail.com', 'Madison', 'SD', '(605) 759-8755', '4561 Marble Cir. 57104', '2022-10-30' ),
('JamisonBond!!!', 'Jamison', 'Bond', 'User', '2003-06-20', 'Jamesbondlol@gmail.com', 'Brookings', 'SD', '(605) 321-4300', '7309 Medary Ave. 57016', '2022-11-04' ),
('Hailey123456', 'Smith', 'Hailey', 'User', '2001-09-24', 'HySt2107@gmail.com', 'Sioux Falls', 'SD', '(605) 258-4517', '1204 Jeremy St. 57305', '2022-11-21'),
('Jimmy_wade31', 'Jeremy', 'Wade', 'User', '2004-12-22', 'mrjfootball11@gmail.com', 'St. Paul', 'MN', '(620) 789-1432', '8607 Key Circle Dr. 57108', '2021-12-05'),
('MasterCole', 'Cole', 'Masterson', 'User', '2001-06-25', 'Masterson681@gmail.com', 'St. Cloud', 'MN', '(620) 543-2198', '..............', '2022-12-01'),
('NotCartel', 'Cartel', 'Lopez', 'User', '2000-04-05', 'cartel04@gmail.com', 'Watertown', 'SD', '(620) 574-9076','................', '2022-11-14'),
('TopGLogan','Logan', 'Gregg', 'User', '2000-09-11', 'logangregg@gmail.com', 'Sioux Falls', 'SD', '(605) 588-9855', '...............', '2011-04-23');
INSERT INTO item (`name`, sellerID, category, subcategory, `use`, buyNowPrice)
VALUES
("Black Sneakers", "Jeremy_wade31", "Men's Clothing", "Shoes", "Lightly Used", "35.00"),
("Orange Nike Shirt", "Jeremy_wade31", "Women's Clothing", "Outerwear", "Lightly Used", "12.00"),
("Grey Under Armour Shorts", "Jeremy_wade31", " Mens Clothing", "Outerwear", "New", "20.00"),
("Tan Birkenstocks", "Jeremy_wade31", "Women's Clothing", "Shoes", "New", "70.00"),
("Black Sweatshirt", "Jeremy_wade31", "Men's Clothing", "Outerwear", "Warm hoodie", "40.00"),
("Mini Fridge", "Jeremy_wade31", "Home Improvement", "Kitchen", "Very Used", "60.00"),
("Dishwasher", "Jeremy_wade31", "Home Improvement", "Kitchen", "Lightly Used", "120.00"),
("Brown Sleeper Sofia", "Jeremy_wade31", "Home Improvement", "Furniture", "New", "130.00"),
("Coffee Table", "Jeremy_wade31", "Home Improvement", "Furniture", "Very Used", "20.00"),
("Leather Recliner", "Jeremy_wade31", "Home Improvement", "Furniture", "Lightly Used", "100.00"),
("Frisbee","MasterCole","Hobbies","Sporting Goods","New","999.99"),
("Bphone XR","MasterCole","Electronics","Computers","Moderately Used","408.69"),
("LED Banana","MasterCole","Electronics","Gaming","Very Used","87.23"),
("North Face Jacket","MasterCole","Men's Clothing","Outerwear","New","129.99"),
("Fidget Spinner","NotCartel","Hobbies","Board Games","Lightly Used","4.32"),
("Air Jordan 11's","NotCartel","Men's Clothing","Shoes","Very Used","239.99"),
("Bunny Slippers","NotCartel","Women's Clothing","Shoes","Lightly Used","14.99"),
("Red Board Shorts","TopGLogan","Men's Clothing","Pool Wear","New","27.89"),
("Alienware Desktop","TopGLogan","Electronics","Computers","Very Used","875.99"),
("ATH-M50X","TopGLogan","Electronics","Audio","Moderately Used","97.99"),
("Nerf Football","Johnloveslife","Hobbies","Sporting Goods","New","4.99"),
("Bikini","Johnloveslife","Women's Clothing","Pool Wear","Lightly Used","18.99"),
("Supreme Hoodie","NotCartel","Men's Clothing","Outerwear","New","420.69"),
("Red High Heels","Johnloveslife","Women's Clothing","Shoes","Moderately Used","12.99"),
("Vans High-Tops","NotCartel","Men's Clothing","Shoes","New","59.99");

INSERT INTO bid (bid_price, itemID, username, `bid-start-date`, `bid-end-date`)
VALUES
('37.00', '1','Jeremy_wade31', '2022-11-01', '2022-12-01' ),
('80.00', '4', 'Johnloveslife', '2022-10-20', '2022-11-20' ),
('25.50', '3', 'SarahWolfie', '2022-11-12', '2022-12-20' ),
('115.00', '10', 'JamisonBond!!!', '2022-11-24', '2022-12-02'),
('130.00', '7', 'Hailey123456', '2022-12-01', '2022-12-18'),
('22.25', '9', 'Jimmy_wade31', '2022-11-13', '2022-12-05');

 INSERT INTO transaction (processingISComplete, bidID, `transact-date`)
VALUES
('1','1', '2022-12-01' ),
('1','2', '2022-11-20' ),
('1','3', '2022-12-20' ),
('1','4', '2022-12-02'),
('1','5', '2022-12-18'),
('1','6','2022-12-05');

INSERT INTO profile (description, username)
VALUES
('Enjoy sports and the outdoors. I am also into interier design and home remodeling','Jeremy_wade31'),
('Love working out and Cardio. I am always looking for new clothes and','Johnloveslife'),
('School is my passion. I love learning', 'SarahWolfie'),
('I am addicted to buying funiture!!!', 'JamisonBond!!!'),
('Looking for makeup and hairproducts','Hailey123456'),
('Love Hunting and Fishing and all outdoor activities','Jimmy_wade31');

 INSERT INTO review (rating, profileID, `comment`)
 VALUES
 ('5', '1', 'I really Love the product it is lightly used and it fits me well.'),
 ('3', '1', 'It accomplishes what I need it to, but nothing special!'),
 ('4', '1', 'Minory used and it fits in my room well, no complaints.'),
 ('2', '1', ' Waste of Money, do not buy.'),
 ('2', '1', 'There were holes in the shorts I bought.'),
 ('5', '1', 'Great Product!');